# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghofig < Formula
  desc "A TUI-based CLI tool for browsing and managing Ghostty terminal configuration"
  homepage "https://github.com/intaek-h/ghofig"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intaek-h/ghofig/releases/download/v0.1.2/ghofig_0.1.2_darwin_amd64.tar.gz"
      sha256 "99385698318b65ca3494b4bc91da441153fbd7e5f22e9f7430dddddebf481fe5"

      def install
        bin.install "ghofig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intaek-h/ghofig/releases/download/v0.1.2/ghofig_0.1.2_darwin_arm64.tar.gz"
      sha256 "6b9de708771025794e63c6df5de97c40bba0ef6147dc3ba2b1d226aaab1b2a8b"

      def install
        bin.install "ghofig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/intaek-h/ghofig/releases/download/v0.1.2/ghofig_0.1.2_linux_amd64.tar.gz"
      sha256 "32206cab4c1cffcbdc53644bfc823633b83432e77d5b67775d8c7a3f0e22043a"
      def install
        bin.install "ghofig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intaek-h/ghofig/releases/download/v0.1.2/ghofig_0.1.2_linux_arm64.tar.gz"
      sha256 "885a06b59ce0acca34e6af29a541e147b501345eafaabcd12712041c6462132e"
      def install
        bin.install "ghofig"
      end
    end
  end

  test do
    system "#{bin}/ghofig", "--version"
  end
end
