# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghofig < Formula
  desc "A TUI-based CLI tool for browsing and managing Ghostty terminal configuration"
  homepage "https://github.com/intaek-h/ghofig"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/intaek-h/ghofig/releases/download/v0.1.0/ghofig_0.1.0_darwin_amd64.tar.gz"
      sha256 "0d4e1c134cb4a809f7ec1b7ce61b8befa7840e7ee85dd504a9101bb412581ecd"

      def install
        bin.install "ghofig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/intaek-h/ghofig/releases/download/v0.1.0/ghofig_0.1.0_darwin_arm64.tar.gz"
      sha256 "025e2d914f1a111d9e6c11ff4f73097359532735dac2eafdeb68966ccca5447f"

      def install
        bin.install "ghofig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/intaek-h/ghofig/releases/download/v0.1.0/ghofig_0.1.0_linux_amd64.tar.gz"
      sha256 "68d27141fc825e90871d02dc0aec9112780cbe42533929c6d9b3e5b37aace97e"
      def install
        bin.install "ghofig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/intaek-h/ghofig/releases/download/v0.1.0/ghofig_0.1.0_linux_arm64.tar.gz"
      sha256 "e50d31fad2a9083726dae9c53e7be720a2cfc5910b5971bf1f53456b484f56af"
      def install
        bin.install "ghofig"
      end
    end
  end

  test do
    system "#{bin}/ghofig", "--version"
  end
end
